name: Lint Title

on:
  pull_request:
    branches: ["*"]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    name: Validate PR Title
    steps:
      - uses: amannn/action-semantic-pull-request@c3cd5d1ea3580753008872425915e343e351ab54 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
